CREATE DATABASE IF NOT EXISTS product_master;
CREATE DATABASE IF NOT EXISTS keycloak;
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'root'@'%';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;